import type { Metadata } from "next";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Resume Editor | Simple Resume",
  description: "Generated by create next app",
};

export default function Layout({ children }: PropsWithChildren) {
  return <>{children}</>;
}
